sudo: required
services:
  - docker

branches:
  only:
  - master
  
before_install:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

script:
  - docker build -t shunk031/mecab-neologd-py3 .
  - export TAG=`date +%Y.%m.%d`
  - docker tag shunk031/mecab-neologd-py3 shunk031/mecab-neologd-py3:$TAG
  - docker push shunk031/mecab-neologd-py3:$TAG
  - docker tag shunk031/mecab-neologd-py3 shunk031/mecab-neologd-py3:latest
  - docker push shunk031/mecab-neologd-py3:latest

env:
  global:
    - secure: "vf8bQuAyqnWV63+Wn/b/6lf3OzbTsWG4xTt0i66dddoP85VQrJr3War/d3aGGDZL7W5+B4EXvTehzVpqfn/WbDC4LxwPKrIQxKUZMBVvqubAY7YKzjm/CSfdwccYR/a6hYd8sre0elyOK3on9QUqD/FLlDGKpx6tyyNaU/NuXeoWTZiHFjwVl6O6x+AmQdKohc+zr7TAN08IULga1I3ONXyp4tkJpRvCrErykBiRbHzSNro6ekMdy7O9erUwSuHC/vO/mjpVWkibRlZTRYDUfNs7wVOiKR/KJSo4UqWjnXqg4MEF1L1EBT0dcppHBry1DTgkHzRtv+1qJSv0Jhi4dz1BvsAmGKuZYQq85NMMvWTjpq55UdNLYu3rhhpeshvrihGrHpA/XP2hWvGsHi2h2J7kWzzffMokayjnVWPg3r38tC5iLR+SOUqZd5oUlHgEHruA/jI58Ca6Ea/PM1P5TuFWYSc4fxdzJ/EtRmZ0P468LXcMVA0RlBM5SogpLDUGzpwtfR9hs2Je49sQ/7tnhJ80e9vK5xcW8QX2e8SKBlfTAzrI7d7Q1EvxllS63adqudiuePnL0zaAZHevhD0kOub07/M9P+lnbAjXPHlzw4O9iD/7My2RP8Mu4zxJ9DdOruiMHP6AlhcZF6DsIWvP9gwUWBmI88Ph+ZDk8a0DL3w="
    - secure: "UPc6W5FUhG8Z2Zb1yWwvhlIY4tCAbqcbjN7cXxEFJ7L2g6Gbqai+E1MFvtGh4B4wGf1FVjoKdN32+yHl4nx5Hwx93GZl+uutHhMGvA1eNRAMuL68cGqD5thRHCSkg7bNPeNDIm3DJwbleCBxEssTfuomC7DqyE85FVHPo2sA9m2wd2t6r8shYC/DMdLtUJXmCncS9PktVNxmJtYoYWu9hCMfXCG4TTzoEBOWnJInWZEAPDjZSced+MB8DHEAK3l9JtANjUIdQNzo0g5jVxSEvDrqU7H1Ns4GYtJOd0gDa4F5c2zPhQVGivX6sU8hpY3zh72usx1pcIe83lQORYM5Kt7Eay8jng1yODSKJGx40ySAggR73gTsnUpNfn6BCuWa89aqJugjLDG1wU10OY/z++tsjOKt1KWMBThM2+e8Bex+rJagiNXT3GUr+QUCK/2yKA+3bjOTUqne+zg3KO0a2GBuxk75eoyTgFxvwgxqqy1YoqdD4FFQ9SWSOxUkU0u4/2qaaRnCLHCo+XxEhlgBc/65axPaEViUulU7x0mXD9HVrMZA5VdTOgrjRqR9dcIeSRnAQxiCUbYYwoyPWLWa7LOqLJa6OMEQs3SUfDV6Ic2bN30tGE2iWd2omsnO9C8+dsazKB8UlC9owzqjhCzpvYgDIXeCVYXVUSyxecKMnCE="
    - secure: "c7CnR26W3NWpcD/cxsNGMAEyGTP2s3WQGcnuj9k8HQpGt6Gpyvma4wA4ulebRw3dYuFi/+WEfEapGV/m3yNih5ZhtuPC2EGaBAnevqoGSyG/Cjv24whpqiWPruoYaFdb4c0GbwL8ckkKqAji9bn8WWGJJucbVyJd7ZMpGQ+GPHwsNcQEne8ETn7Y8WBT2fs6ygZotYYafaIXpc5YsI8pdNBvhdTNIMS/Sf47IPI85Gw/u3VgVZS3Ls4nD+hOFHvpLdJHTGRnBgHZ3Hy6K1D0aHBhI6RyfgILS1YGsvU5KfbKNSHlnlvPs+YC65ZOhTeGkpYvEBVhDj70gbUrxn2CpxLFISU3T7uMtrlUYbN9YNmjYiSSMpgpbp+doi57BYb0V/YGZgyoThdzhPJlV2+PV5CDN7Z2xY19N+WsKHGqzcIDUg9WEHLxvE6otGLHoG1UUqOpBVPFehL1Au8pAiyJmwAg7SQvPKzGvaWPBaDCIpK+O6ABCMSFyKthDhCxAxmWqivp+zvFFChcLbzV4Qwlk4CJRJII3JM+9rtXbbsQAenSmOI/h/64urUVhOKrptB4OMS1hlWaoVjX+iA50cFdcQjIKk0ZvVi8V7KFSqtxyuIWpnjxg9FqRpeTK9mqNhGh4hWpuwFLWHjsmwVNlj2WyH2MxPc16KtVL2NsS9YuVBM="

notifications:
  slack:
    secure: "VBK5ebHZZm0vHMZ3L9RXQlhoD3IyujY27qRs98MxZwcjxZezANyT2+J7VEJHpVvW65dVPHUq31w1n2Gt7VHWV1idwOuf3bX+KpqQV1OcrFdjvh0xrEubSb0BZuGP3nbkRJebbXppG+ByHofFOE6qtFgik/1fezvMLZ6GKGSzPKQQa3gxBgiJK02K8Gl4vjXPt3Df37t0ELJd010tDnoTRYRxIFRrn6ZlujgZUF7D5La9L591IWZChig2BGAOgyLlIs+RtRI8vw8aY5GkFGo5/IYlHxENyR1PyHYBAxpGU6zufcba8mjuqNY69+yN46ixM8I7fgAWhjRVoZhX35lBpGLIOx07d4NA9GAMU8+6Hbo+goNZ+14gdmIfalxTy0BcNj31I8NKOHeRaST031/lw9dgpdpI0s+0uAVoY9hgvioZk6PDuQFF0CK2q1ZGRdetL6qG+khkyr/UB/1IWofM9rWgLiWgLezIOjqzbIh+7NRPdcUMGgVEr0ZPDyk+owam1V1hj1C04bxpPdNlC8pdCGWKwlFf3xZVJR+4RdNkyUuR+G0uJuMh3lRxGPfziyhgQeEEMC4TzmWCvFn+c1W6Q5UdMQGmM5pVzC2VYzoSdlhVGkeW5ESthhidggBVAjR6sfM1ZMB2Augy7AQMM1q6Ft+GdVJVunTOMPzPx64B3CI="
