sudo: required
services:
  - docker

branches:
  only:
  - master
  
before_install:
  - docker login --username=DOCKER_HUB_USERNAME−−password=DOCKER_HUB_PASSWORD

script:
  - docker build shunk031/mecab-neologd-py3 .

deploy:
  - export TAG=`date +%Y.%m.%d`
  - docker tag shunk031/mecab-neologd-py3 shunk031/mecab-neologd-py3:TAG
  - docker push shunk031/mecab-neologd-py3:TAG
  - docker tag shunk031/mecab-neologd-py3 shunk031/mecab-neologd-py3:latest
  - docker push shunk031/mecab-neologd-py3:latest

env:
  global:
    - secure: "zX2DGX3+ZzaDyZ5QMb6baANLbIahEcPUWThZ8XBNBc9cHuvvJhGL1vH0e2Bm3InvKIZxB6dGb8BnJe2ntEXA6c1gThgPwrvR+aEM2dd1V/qTGGlwCrAslUhxuVb6Am1TEefhHYG1A+JYuSyEmlJmxkbtAJOZ8XH2PZzmm/gR4RfDqzACCmBo9vWMC5fX078f2noidDxtuI1RnHSNX5zxUJLCm27nZRodSGn6taiTYHj6vpLeAjZftp7etiUO/G0nA7PQIvsIAj8YZV+0ybEXsMARkz32gmdJ1DUztVHnQscY6dUoRkY2x4k5iaKbqXG8teTPkkloTwiN/2R3cAtzD4R2qu2GN0xrtAeP6vTILPxJFoxE/3ESBsREpUB5sJI1SYc/nwzVUChNFrTQEuyelM+8alQDLVJ1X6U4QXFawpXXri+hTwh7E2TIqHt39O5J5TYubWhp2Yr+SLwVyVnlKnjgfRhlu6LBACeQguwzvNhGsB2+Suel5c8ob0wdarFjoPTEoDSB5iim6vwCG/ggYY9vK87z5Diq/tgNwhet82RgoVq/sHtqUloV6cS7s4Dfazqs3WT9DdSXLNFzUKpvYfdZqHPBkALWXHvbsakAVLzzLRxbV6F6NfSJoK5XW4dnqwoagwenn4vpZuqXrMukYiPRQK36L6yBcB2xTUbffss="
    - secure: "R5U7fOoQI5a58efRhuoaT8pIJ8ANYP5wQFuhXY4KozxSzmaFu+Kxj6qj5/HGequuBrj1e300oY9ejUe38GWrU06eJLrU502Unedk4AiBqdaZrhofJKgWNN7GKkH8ERR8bU9Y+R3zT+UEtdrueAfTvhq/rWxOOj5ljn1z/j/jRoD2dwyDDRfGVXGOrbVvJ1+km6p3PwfYA5Lj+y70k221CGiHrvIDHiZAA1KihpsM27NIIop9FeE9gCadaVqEk+AdpRQPefWqPq3poZ9ieeohbKSGxdKiDHyxuUS2nUFfpSoNkmXySRpAjwUSU0K7rv3B1EEeR4NhWK+c8wCsTw7h37D7W/ujFduBlbimdrA1ip3DFvjOgHv73s7CfAdqGS2Pij8Qofj/uE6hU83KZbtIewTmw35+dR5YJQncvhyJ6hKVE5zMoK9/niSXsIhm1QY9pm0VeQkhjdZHvhluwNrw+sKhT80SMzYLTNxKDSztlHK+TqX01Ghi4TdyXtXq5NRUqlAvubcIEfMv4KW5k/lbxS5jjxhnRMnpu2DffUx4G8y4l791I1ChoJjs8qs/weh3nziSbFGaaWDEOOB8xWBcg1TBAFwOi/cbv/Y8qjyjuSCOZMMbWtSgsxkX7JR63ZVKiAicthn1HaFwRauBWqD/zTO/FsB0OhOsHQgEQrkalgE="

notifications:
  slack:
    secure: "VBK5ebHZZm0vHMZ3L9RXQlhoD3IyujY27qRs98MxZwcjxZezANyT2+J7VEJHpVvW65dVPHUq31w1n2Gt7VHWV1idwOuf3bX+KpqQV1OcrFdjvh0xrEubSb0BZuGP3nbkRJebbXppG+ByHofFOE6qtFgik/1fezvMLZ6GKGSzPKQQa3gxBgiJK02K8Gl4vjXPt3Df37t0ELJd010tDnoTRYRxIFRrn6ZlujgZUF7D5La9L591IWZChig2BGAOgyLlIs+RtRI8vw8aY5GkFGo5/IYlHxENyR1PyHYBAxpGU6zufcba8mjuqNY69+yN46ixM8I7fgAWhjRVoZhX35lBpGLIOx07d4NA9GAMU8+6Hbo+goNZ+14gdmIfalxTy0BcNj31I8NKOHeRaST031/lw9dgpdpI0s+0uAVoY9hgvioZk6PDuQFF0CK2q1ZGRdetL6qG+khkyr/UB/1IWofM9rWgLiWgLezIOjqzbIh+7NRPdcUMGgVEr0ZPDyk+owam1V1hj1C04bxpPdNlC8pdCGWKwlFf3xZVJR+4RdNkyUuR+G0uJuMh3lRxGPfziyhgQeEEMC4TzmWCvFn+c1W6Q5UdMQGmM5pVzC2VYzoSdlhVGkeW5ESthhidggBVAjR6sfM1ZMB2Augy7AQMM1q6Ft+GdVJVunTOMPzPx64B3CI="
